name: Challenge1

on: 
  workflow_dispatch:

jobs:
  job1:
    name: Job 1 - Basic Setup
    runs-on: ubuntu-latest
    steps:
      - name: setup
        run: |
          echo "Date: $(date)"
          echo "Working directory: $(pwd)"
          echo "Directory contents:"
          ls -la

  job2:
    name: Job 2 - Python and Artifact
    runs-on: ubuntu-latest
    steps:
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: print python version
        run: python --version

      - name: set up pandas
        run: pip install pandas

      - name: create artifact
        run: |
          echo "# This is my python artifact" > artifact.py
          python artifact.py
