name: pythonworkflow
on: workflow_dispatch

jobs:    
    data_pipeline:
        name: data_pipeline
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v4
            - run: |
                echo ${{ github.workspace }}
                echo $GITHUB_WORKSPACE
            - name: clean_data
              run: |
                pwd
                ls -la
                pwd
                cd ModelCleaning
                pip install pandas
                python cleandata.py
            - name: train_test_dataset
              run: |
                pip install scikit-learn joblib
                python ModelCleaning/train_test_dataset.py


