name: tutorial1
on: push

jobs:
  job1:
    name: job1
    runs-on: ubuntu-latest
    steps:
    - name: step1
      run: echo "Hello from job1"
    - name: step1_1
      run: echo "Today's date is $(date)"
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: check version of python
      run: python --version
  job2:
    name: job2
    runs-on: windows-latest
    steps:
    - name: step2
      run: echo "hello from job2"
    - name: step2_2
      run: echo "Today's date is $(date)" 
  job3:
    name: job3
    runs-on: ubuntu-latest
    steps:
      - name: step3
        run: echo "hello from job3"
      - name: step3_1
        run: echo "Today's date is $(date)"
  job4:
    name: job4
    needs: [job1, job2]
    runs-on: ubuntu-latest
    steps:
      - name: step4
        run: echo "I am job 4"
